aks_loadbalancer_ip    = "4.157.9.12"
resource_prefix        = "cmtr-31zawnrd-mod9"
location               = "East US"
resource_group_name    = "cmtr-31zawnrd-mod9-rg"
vnet_name              = "cmtr-31zawnrd-mod9-vnet"
vnet_address_space     = ["10.0.0.0/16"]
aks_subnet_name        = "aks-snet"
firewall_subnet_prefix = "10.0.1.0/24"
aks_cluster_name       = "cmtr-31zawnrd-mod9-aks"
